server:
  port: 80

spring:
  security:
    user:
      name: test
      password: 12345
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  livereload:
    enabled: true

  main:
    banner-modeL: "off"
  application:
    name: shop
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webdb
    username: dbuser
    password: 12345
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      thymeleaf: DEBUG
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
